name: Playwright tests working web-service
on:
  push:
    branches: [ test-branch ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  packages: write
jobs:
  testE2E:
    timeout-minutes: 30
    runs-on: [ self-hosted, ARM64 ]
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      KEYCLOAK_URL: ${{ secrets.KEYCLOAK_URL }}
      CLIENT_CODE: ${{ secrets.CLIENT_CODE }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
      ALLURE_TESTOPS_TOKEN: ${{ secrets.ALLURE_TESTOPS_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Grant Docker socket permissions
        run: sudo chmod 666 /var/run/docker.sock
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
            
      - name: Install dependencies
        run: npm ci
        
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Clean previous Allure results
        run: |
          rm -rf allure-results || true
          mkdir -p allure-results
        
      - name: Run Playwright tests
        run: |
          npx playwright test specs/ --reporter=list --reporter=junit --reporter=allure-playwright

      # Установка и запуск allurectl для загрузки результатов
      - name: Install allurectl
        if: always()
        run: |
          curl -o allurectl -L "https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_arm64"
          chmod +x allurectl
          sudo mv allurectl /usr/local/bin/
          
      - name: Upload results to Allure TestOps
        if: always()
        run: |
          allurectl upload allure-results \
            --endpoint https://allure.autotests.cloud \
            --project-id 4736 \
            --token ${{ secrets.ALLURE_TESTOPS_TOKEN }} \
            --launch-name "GitHub Run #${{ github.run_number }}"
        
      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: test-results
          path: test-results
          retention-days: 20
          
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: allure-results
          path: allure-results
          retention-days: 30
          
      - name: Generate Allure Report
        if: always()
        run: |
          npm install -g allure-commandline@2.x --force
          allure generate allure-results --clean -o allure-report
          
      - name: Setup Telegram Configuration
        if: always()
        continue-on-error: true
        run: |
          # Создаем директорию и генерируем конфигурацию с подстановкой переменных
          mkdir -p notifications/templates
          
          # Скачиваем jar-файл
          curl -o notifications/allure-notifications-4.9.0.jar -L https://github.com/qa-guru/allure-notifications/releases/download/4.9.0/allure-notifications-4.9.0.jar
          
          # Создаем telegram.json с подстановкой переменных окружения
          cat > notifications/telegram.json << EOF
          {
            "base": {
              "logo": "",
              "project": "QA.GURU_diplom",
              "environment": "GitHub Actions",
              "comment": "some comment",
              "reportLink": "https://kseniayari.github.io/QA.GURU_diplom/",
              "language": "ru",
              "allureFolder": "allure-report",
              "enableChart": true,
              "enableSuitesPublishing": false,
              "customData": {}
            },
            "telegram": {
              "token": "$TELEGRAM_TOKEN",
              "chat": "$TELEGRAM_CHAT",
              "replyTo": ""
            }
          }
          EOF
          
          # Создаем шаблоны
          echo '<#macro formatTime time><#if time??>${time}</#if></#macro>' > notifications/templates/commons.ftl
          
          cat > notifications/templates/telegram.ftl << 'EOL'
          <#import "commons.ftl" as commons>
          {
            "message": "<b>${report.name}</b>\n\n<b>Environment:</b> ${report.environment}\n<b>Comment:</b> ${report.comment}\n<b>Duration:</b> <#if report.time??>${report.time.duration}</#if>\n\n<b>Текущий запуск:</b>\n✅ Успешно: ${report.statistic.passed}\n❌ Упало: ${report.statistic.failed}\n⚠️ Сломано: ${report.statistic.broken}\n\n<a href='${report.url}'>Отчет на GitHub Pages</a>",
            "parse_mode": "HTML"
          }
          EOL
          
      - name: Send Telegram Notifications
        if: always()
        continue-on-error: true
        run: |
          # Запускаем отправку уведомлений, используя существующий файл конфигурации
          java "-DconfigFile=notifications/telegram.json" \
            "-Dbase.reportLink=https://kseniayari.github.io/QA.GURU_diplom/" \
            -jar notifications/allure-notifications-4.9.0.jar
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
          
      - name: Upload Allure HTML report
        uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: allure-report
          path: allure-report
          retention-days: 30
          
      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-report